### PR TITLE
TextLayout: Skija implementation prototype, only windows.

### PR DESCRIPTION
**Pull request by DenisUngemach**

### CODE REVIEW

**Comment by fedejeanne** [comment]
Hi @DenisUngemach . I just wanted to point out that since the "official" `TextLayout` is now `TextLayoutOld`, it's a bit more difficult to stay synchronized with the [official `origin/master` of SWT](https://github.com/eclipse-platform/eclipse.platform.swt).

In particular, I just did a rebase on `origin/master` and simply ignored [the latest changes made in `TextLayout`](https://github.com/eclipse-platform/eclipse.platform.swt/commits/master/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/TextLayout.java).

image

I will push the rebase in a minute. Please make sure to **pull**.

**Comment by DenisUngemach** [comment]
I think we could also delete the TextLayout_Old class. I needed it for the development.

**Comment by HeikoKlare** [comment]
You have _rebased and force pushed_ the main development branch `skija`. Please _never_ do that, except if everyone involved in the development knows about that and agrees on it. I am not even sure how that was possible with the branch protection rule in place. I have reset the `skija` branch to the state before the force push.

**Comment by fedejeanne** [comment]
I rebased on `origin/master`. How is that bad?

**Comment by HeikoKlare** [comment]
You must not rebase a main development branch (or actually any commonly used development branch). In most repositories, it is forbidden to rewrite the history of the main development branch as this introduced a bunch of problems. If needed, you can only do that in a coordinated way, where everyone involved is informed about that. That why we, as usual, have an according protection rule for that in place.
Many people have a local downstream branch the main development that should _only_ be fast forwarded on updates and _not_ be rewritten. In addition, every feature/PR branch is based on that main development branch and _not_ on origin/master. That's why all pull requests were broken after that rebase because their target branch was rewritten, thus leading to a changed common ancestor of feature and traget branch (several hundred commits ago), leading to hundrets of commits in those PRs to be merged. Just to mention few of the issues that arise from replacing a main development branch.

**Comment by DenisUngemach** [comment]
I think we should remove some branches. One of them is probably the master branch. 

I will create an issue for that.

**Comment by HeikoKlare** [comment]
Yes, let's have separate discussion about that to clarify which branches we use in which way. We need to be aware that this repo is a fork of the original SWT repository, with `master` being the branch synchronized with remote's `master`.

**Comment by fedejeanne** [comment]
My bad, rookie mistake.

So, should we merge `origin/master` into `prototype-skija/skija` instead?

**Comment by HeikoKlare** [comment]
Why do we need to update at all? Is it about adapting to SWT API changes?
We are currently based on Eclipse 4.34 / SWT 3.128 release versions. In case we (frequently) want to update, we should rather do that only for release version and not for any intermediate states. Otherwise, you will need to have according state of all other SDK bundles as well (to avoid incompatibilities leading to errors), which is hard to communicate and setup properly.
As an alternative, we may update the readme/contributing information to refer to the SWT/Eclipse release we currently base on and how to set up development for that. I see that we refer to 2024-09 or newer (https://github.com/swt-initiative31/prototype-skija?tab=readme-ov-file#setup), but we should actually refer to 2024-12 explicitly, as that's the one we are currently based on.

**Pull request merged**
